export const fontSizes = {
  xxs: '0.625rem',
  xs: '0.75rem',
  sm: '0.875rem',
  md: '1rem',
  lg: '1.125rem',
  xl: '1.25rem',
  '2xl': '1.5rem',
  '4xl': '2rem',
  '5xl': '2.25rem',
  '6xl': '3rem',
  '7xl': '4rem',
  '8xl': '4.5rem',
  '9xl': '6rem',
} as const

export const fontSizeVariants = {
  xxs: { fontSize: '$xxs' },
  xs: { fontSize: '$xs' },
  sm: { fontSize: '$sm' },
  md: { fontSize: '$md' },
  lg: { fontSize: '$lg' },
  xl: { fontSize: '$xl' },
  '2xl': { fontSize: '$2xl' },
  '4xl': { fontSize: '$4xl' },
  '5xl': { fontSize: '$5xl' },
  '6xl': { fontSize: '$6xl' },
  '7xl': { fontSize: '$7xl' },
  '8xl': { fontSize: '$8xl' },
  '9xl': { fontSize: '$9xl' },
}
